export const JOB_TITLES = [
    "MERN Stack Developer",
    "MEAN Stack Developer",
    "Node.js Developer",
    "React Developer",
    "Software Engineer",
    "Software Developer",
    "Application Developer",
    "Backend Developer",
    "Frontend Developer",
    "Full Stack Developer",
    "Web Developer",
    "Mobile App Developer",
    "iOS Developer",
    "Android Developer",
    "Systems Developer",
    "Embedded Software Engineer",
    "Game Developer",
    "Desktop Application Developer",
    "Platform Engineer",
    "Web Application Engineer",
    "UI Developer",
    "UX Engineer",
    "Progressive Web App (PWA) Developer",
    "CMS Developer",
    "WordPress Developer",
    "Shopify Developer",
    "API Developer",
    "Web Performance Engineer",
    "SEO Software Engineer",
    "DevOps Engineer",
    "Cloud Engineer",
    "Cloud Solutions Architect",
    "Site Reliability Engineer (SRE)",
    "Infrastructure Engineer",
    "Platform Operations Engineer",
    "Build & Release Engineer",
    "CI/CD Engineer",
    "Cloud Security Engineer",
    "Kubernetes Engineer",
    "Cybersecurity Engineer",
    "Information Security Analyst",
    "Network Security Engineer",
    "Security Operations Center (SOC) Analyst",
    "Ethical Hacker",
    "Penetration Tester",
    "Application Security Engineer",
    "Cloud Security Architect",
    "Malware Analyst",
    "Digital Forensics Analyst",
    "Data Scientist",
    "Data Analyst",
    "Data Engineer",
    "Big Data Engineer",
    "Machine Learning Engineer",
    "AI Engineer",
    "Deep Learning Engineer",
    "NLP Engineer",
    "Computer Vision Engineer",
    "Research Scientist (AI)",
    "Robotics Software Engineer",
    "Automation Engineer",
    "IoT Developer",
    "IoT Solutions Architect",
    "Embedded Systems Engineer",
    "Control Systems Engineer",
    "Firmware Engineer",
    "Mechatronics Software Engineer",
    "Industrial Automation Engineer",
    "Smart Systems Engineer",
    "Research Engineer",
    "Computer Science Researcher",
    "Teaching Assistant (CS)",
    "Assistant Professor (CS)",
    "Lecturer (Computer Science)",
    "Academic Research Scientist",
    "Doctoral Research Fellow",
    "Postdoctoral Researcher",
    "Computational Scientist",
    "Algorithm Research Engineer",
    "Algorithm Engineer",
    "Systems Engineer",
    "Operating Systems Engineer",
    "Compiler Engineer",
    "Low-Level Software Engineer",
    "Performance Engineer",
    "Storage Engineer",
    "Kernel Developer",
    "Distributed Systems Engineer",
    "Networking Engineer",
    "QA Engineer",
    "Software Test Engineer",
    "Automation Test Engineer",
    "Manual Test Engineer",
    "Performance Test Engineer",
    "Security Test Engineer",
    "Reliability Engineer",
    "Test Architect",
    "Validation Engineer",
    "Quality Analyst",
    "UI/UX Designer (Technical)",
    "Product Designer (Tech)",
    "Interaction Engineer",
    "Design Technologist",
    "Creative Technologist",
    "Blockchain Developer",
    "Web3 Engineer",
    "Smart Contract Developer",
    "AR Developer",
    "VR Developer",
    "XR Engineer",
    "Metaverse Engineer",
    "Quantum Computing Engineer",
    "Edge Computing Engineer",
    "FinTech Software Engineer",
    "Technical Product Manager",
    "Product Engineer",
    "Engineering Manager",
    "Technical Lead",
    "Team Lead (Software)",
    "CTO (Chief Technology Officer)",
    "Solutions Architect",
    "Enterprise Architect",
    "Technical Consultant",
    "Digital Transformation Engineer",
    "Tools Engineer",
    "Developer Advocate",
    "Technical Evangelist",
    "Support Engineer",
    "Application Support Engineer",
    "Platform Support Engineer",
    "Technical Account Manager",
    "Customer Success Engineer",
    "Systems Support Engineer",
    "IT Engineer",
    "Freelance Software Developer",
    "Independent Consultant (CS)",
    "Startup Founder (Tech)",
    "Indie Hacker",
    "SaaS Builder",
    "Open Source Maintainer",
    "Technical Blogger",
    "YouTube Tech Creator",
    "Coding Instructor",
    "Tech Influencer",
    "Bioinformatics Engineer",
    "HealthTech Engineer",
    "EdTech Engineer",
    "LegalTech Engineer",
    "GovTech Engineer",
    "AI Ethics Engineer",
    "Sustainability Tech Engineer",
    "Digital Twin Engineer",
    "Simulation Engineer",
    "Computational Engineer"
];
